#!/usr/bin/env bash
# Shared start-up steps for MiroTalk on the OT theatre machines, sourced by start-mirotalk.sh
# (native, Node.js) and start-mirotalk-docker.sh: the LAN IP for WebRTC, the join address and QR
# data for the pages (public/js/join-url.js), and the machine's own certificate if set up.
# Expects to run in the repository folder.

# Active LAN IP = source address used to reach the internet (interface with the
# default route — i.e. the WiFi where laptops are, not the camera ethernet).
detect_ip() {
    local ip
    ip="$(ip -o route get 8.8.8.8 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
    if [ -z "${ip:-}" ]; then
        ip="$(ip -4 -o addr show scope global 2>/dev/null \
              | awk '{print $4}' | cut -d/ -f1 \
              | grep -vE '^(172\.1[7-9]|172\.2[0-9]|172\.3[01])\.' | head -1)"
    fi
    echo "${ip:-127.0.0.1}"
}

LAN_IP="$(detect_ip)"
export SFU_ANNOUNCED_IP="$LAN_IP"

# Publish the current LAN join URL so the landing page can show it. Regenerated
# on every launch, so the URL displayed is always the correct, current IP.
mkdir -p public/js
IP_ORIGIN="https://${LAN_IP}:3010"
[ "$LAN_IP" = "127.0.0.1" ] && IP_ORIGIN=""
# The machine's mDNS name (ot_qt_app/scripts/setup-conference.sh): a fixed address that stays the
# same when the IP changes. The IP stays as a fallback for devices that cannot resolve .local.
OT_NAME="$(cat .ot-conference-name 2>/dev/null || true)"
if [ -n "$OT_NAME" ]; then
    LAN_ORIGIN="https://${OT_NAME}.local:3010"
    FALLBACK_ORIGIN="$IP_ORIGIN"
else
    LAN_ORIGIN="$IP_ORIGIN"
    FALLBACK_ORIGIN=""
fi
cat > public/js/join-url.js <<EOF
// Auto-generated by ot-prepare.sh on each launch — do not edit.
// The address others on the network join at. Room links and QR codes use it instead of
// "localhost" (the OT app opens the room on this PC as localhost).
window.OT_LAN_ORIGIN = '${LAN_ORIGIN}';
window.OT_FALLBACK_ORIGIN = '${FALLBACK_ORIGIN}';
window.otShareOrigin = function () {
    var host = window.location.hostname;
    var local = host === 'localhost' || host === '127.0.0.1';
    return local && window.OT_LAN_ORIGIN ? window.OT_LAN_ORIGIN : window.location.origin;
};
window.addEventListener('DOMContentLoaded', function () {
    var url = window.otShareOrigin();
    var el = document.getElementById('lanJoinUrl');
    if (el) { el.textContent = url; el.setAttribute('href', url); }
    var qr = document.getElementById('lanJoinQr');
    if (qr && typeof QRious === 'function') {
        new QRious({ element: qr, value: url, size: 112, background: '#ffffff', foreground: '#0f1722', padding: 0 });
        document.getElementById('lanJoinQrBox').style.display = 'block';
        document.getElementById('lanJoinQrHint').style.display = 'inline-flex';
    }
    var fb = document.getElementById('lanJoinFallback');
    if (fb && window.OT_FALLBACK_ORIGIN && url !== window.OT_FALLBACK_ORIGIN) {
        fb.querySelector('a').textContent = window.OT_FALLBACK_ORIGIN;
        fb.querySelector('a').setAttribute('href', window.OT_FALLBACK_ORIGIN);
        fb.style.display = 'inline-flex';
    }
});
EOF


# This machine's own certificate (ot_qt_app/scripts/setup-conference.sh) instead of MiroTalk's
# demo certificate, whose private key is public
OT_HAS_OWN_CERT=0
if [ -f app/ssl-ot/cert.pem ] && [ -f app/ssl-ot/key.pem ]; then
    OT_HAS_OWN_CERT=1
fi
