#!/usr/bin/env bash
#
# Starts MiroTalk SFU in Docker with the announced WebRTC IP auto-detected from
# the machine's current active network. Re-detects on every launch, so moving
# the system to a different WiFi/LAN just works.
#
set -euo pipefail

cd "$(dirname "$0")"

# Active LAN IP = source address used to reach the internet (interface with the
# default route — i.e. the WiFi where laptops are, not the camera ethernet).
detect_ip() {
    local ip
    ip="$(ip -o route get 8.8.8.8 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
    if [ -z "${ip:-}" ]; then
        ip="$(ip -4 -o addr show scope global 2>/dev/null \
              | awk '{print $4}' | cut -d/ -f1 \
              | grep -vE '^(172\.1[7-9]|172\.2[0-9]|172\.3[01])\.' | head -1)"
    fi
    echo "${ip:-127.0.0.1}"
}

LAN_IP="$(detect_ip)"
export SFU_ANNOUNCED_IP="$LAN_IP"

# Publish the current LAN join URL so the landing page can show it. Regenerated
# on every launch, so the URL displayed is always the correct, current IP.
mkdir -p public/js
IP_ORIGIN="https://${LAN_IP}:3010"
[ "$LAN_IP" = "127.0.0.1" ] && IP_ORIGIN=""
# The machine's mDNS name (ot_qt_app/scripts/setup-conference.sh): a fixed address that stays the
# same when the IP changes. The IP stays as a fallback for devices that cannot resolve .local.
OT_NAME="$(cat .ot-conference-name 2>/dev/null || true)"
if [ -n "$OT_NAME" ]; then
    LAN_ORIGIN="https://${OT_NAME}.local:3010"
    FALLBACK_ORIGIN="$IP_ORIGIN"
else
    LAN_ORIGIN="$IP_ORIGIN"
    FALLBACK_ORIGIN=""
fi
cat > public/js/join-url.js <<EOF
// Auto-generated by start-mirotalk-docker.sh on each launch — do not edit.
// The address others on the network join at. Room links and QR codes use it instead of
// "localhost" (the OT app opens the room on this PC as localhost).
window.OT_LAN_ORIGIN = '${LAN_ORIGIN}';
window.OT_FALLBACK_ORIGIN = '${FALLBACK_ORIGIN}';
window.otShareOrigin = function () {
    var host = window.location.hostname;
    var local = host === 'localhost' || host === '127.0.0.1';
    return local && window.OT_LAN_ORIGIN ? window.OT_LAN_ORIGIN : window.location.origin;
};
window.addEventListener('DOMContentLoaded', function () {
    var url = window.otShareOrigin();
    var el = document.getElementById('lanJoinUrl');
    if (el) { el.textContent = url; el.setAttribute('href', url); }
    var qr = document.getElementById('lanJoinQr');
    if (qr && typeof QRious === 'function') {
        new QRious({ element: qr, value: url, size: 112, background: '#ffffff', foreground: '#0f1722', padding: 0 });
        document.getElementById('lanJoinQrBox').style.display = 'block';
        document.getElementById('lanJoinQrHint').style.display = 'inline-flex';
    }
    var fb = document.getElementById('lanJoinFallback');
    if (fb && window.OT_FALLBACK_ORIGIN && url !== window.OT_FALLBACK_ORIGIN) {
        fb.querySelector('a').textContent = window.OT_FALLBACK_ORIGIN;
        fb.querySelector('a').setAttribute('href', window.OT_FALLBACK_ORIGIN);
        fb.style.display = 'inline-flex';
    }
});
EOF

echo "================================================================"
echo " MiroTalk SFU (Docker) starting"
echo "   Announced WebRTC IP : $SFU_ANNOUNCED_IP   (auto-detected)"
echo "   Join from this PC   : https://localhost:3010"
echo "   Join from LAN       : ${LAN_ORIGIN:-https://$LAN_IP:3010}${FALLBACK_ORIGIN:+   (or $FALLBACK_ORIGIN)}"
echo "================================================================"

# Use `docker run` directly — the Compose v1 binary on this host is broken and
# the v2 plugin isn't installed. These flags mirror docker-compose.yml.
# Fully local: no `docker pull`. It downloaded ~1.3 GB from the internet on every start,
# delayed the server (the app's window opened on a "not found" page) and could switch to a
# newer MiroTalk version silently. The image is pinned to the local tag `ot-local`; to
# update on purpose: docker pull mirotalk/sfu:latest && docker tag mirotalk/sfu:latest mirotalk/sfu:ot-local
docker rm -f mirotalksfu >/dev/null 2>&1 || true

# This machine's own certificate (setup-conference.sh) instead of MiroTalk's demo certificate,
# whose private key is public
SSL_MOUNT=()
if [ -f app/ssl-ot/cert.pem ] && [ -f app/ssl-ot/key.pem ]; then
    SSL_MOUNT=(-v "$PWD/app/ssl-ot/cert.pem:/src/app/ssl/cert.pem:ro" -v "$PWD/app/ssl-ot/key.pem:/src/app/ssl/key.pem:ro")
    echo "   Certificate         : this machine's own (app/ssl-ot)"
else
    echo "   Certificate         : MiroTalk demo certificate - run ot_qt_app/scripts/setup-conference.sh"
fi

exec docker run -d \
    --name mirotalksfu \
    --hostname mirotalksfu \
    --restart unless-stopped \
    --network host \
    -e SFU_ANNOUNCED_IP="$SFU_ANNOUNCED_IP" \
    -v "$PWD/app/src/config.js:/src/app/src/config.js:ro" \
    -v "$PWD/.env:/src/.env:ro" \
    -v "$PWD/public:/src/public:ro" \
    "${SSL_MOUNT[@]}" \
    mirotalk/sfu:ot-local
